services:
  db:
    container_name: friendspark-db
    build:
      context: friendspark-backend
      dockerfile: friendspark-backend/Dockerfile-db
    restart: always
    environment:
      POSTGRES_DB: friendspark
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data: